package cli;

import exceptions.MusialException;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import util.Logging;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Handles the {@code expand} task CLI parameters.
 * <p>
 * This class defines the command-line options and validation logic for the {@code expand} task. See {@link #options()} for details.
 */
public class CLIExpand implements CLI {

    /**
     * Defines the command-line options for the `expand` task.
     * <p>
     * This method creates and configures the available command-line options for the `expand` task. The options include:
     * <ul>
     *     <li><b>-I, --storage</b>: Specifies the path to a `.json` or `.json.gz` file generated by the build task of MUSIAL. This
     *     option is required.</li>
     *     <li><b>-V, --vcfFiles</b>: Specifies a list of file or directory paths. All files must be in VCF format. This option is
     *     required.</li>
     *     <li><b>-m, --vcfMeta</b>: Specifies the path to a `.tsv` or `.csv` file containing sample annotations. This option is optional
     *     .</li>
     *     <li><b>-o, --output</b>: Specifies the path to write the output file. If not provided, the input file will be overwritten.
     *     This option is optional.</li>
     *     <li><b>-d, --dry-run</b>: Enables dry-run mode, which reports novel entries without writing the updated storage. This option
     *     is optional.</li>
     * </ul>
     *
     * @return An {@link Options} object containing the defined command-line options.
     */
    public static Options options() {
        Options options = new Options();
        options.addOption(Option.builder("I")
                .longOpt("storage")
                .desc("Path to a .json(.gz) file generated with the build task of MUSIAL.")
                .hasArg()
                .required()
                .build());
        options.addOption(Option.builder("V")
                .longOpt("vcfFiles")
                .desc("List of file or directory paths. All files must be in VCF format.")
                .hasArgs()
                .required()
                .build());
        options.addOption(Option.builder("m")
                .longOpt("vcfMeta")
                .desc("Path to a .tsv or .csv file specifying sample annotations.")
                .hasArg()
                .build());
        options.addOption(Option.builder("o")
                .longOpt("output")
                .desc("Path to write the output file (default: overwrite input file).")
                .hasArg()
                .build());
        options.addOption(Option.builder("d")
                .longOpt("dry-run")
                .desc("Only report on novel entries without writing the updated storage.")
                .build());
        return options;
    }

    /**
     * The path to the input storage file.
     */
    public final Path input;

    /**
     * The path to the output storage file. If {@code null}, the input file will be overwritten.
     */
    public final Path output;

    /**
     * Indicates whether to overwrite the input file. This is {@code true} if {@link #output} is {@code null} and dry-run mode is not
     * enabled.
     */
    public final boolean overwrite;

    /**
     * The list of VCF file paths to expand the storage with.
     */
    public final List<Path> vcfFiles;

    /**
     * A map containing the VCF metadata, with the sample ID as the key and another map of metadata attributes and their values as the
     */
    public final Map<String, Map<String, String>> vcfMeta;

    /**
     * Indicates whether dry-run mode is enabled. If {@code true}, no output will be written.
     */
    public final boolean dry;

    /**
     * Constructs a CLIExpand instance by parsing and initializing the command-line arguments.
     * <p>
     * This constructor processes the provided {@link CommandLine} arguments to extract and validate the parameters required for the
     * `expand` task. It initializes fields such as the input storage path, output path, VCF files, VCF metadata, and the dry-run mode flag.
     * Additionally, it determines whether the input storage file should be overwritten based on the presence of the output path and the
     * dry-run mode.
     * <p>
     * The method performs the following steps:
     * <ul>
     *     <li>Parses the input storage file path using {@link Common#parseInput(CommandLine)}.</li>
     *     <li>Parses the output file path using {@link #parseOutput(CommandLine)}.</li>
     *     <li>Parses the list of VCF files using {@link #parseVcfFiles(CommandLine)}.</li>
     *     <li>Parses the VCF metadata using {@link #parseVcfMeta(CommandLine)}.</li>
     *     <li>Checks if the dry-run mode is enabled and sets the overwrite flag accordingly.</li>
     * </ul>
     * <p>
     * If any required parameter is missing or invalid, appropriate exceptions are thrown.
     *
     * @param arguments The {@link CommandLine} object containing the parsed command-line arguments.
     * @throws MusialException If any required parameter is missing or invalid.
     * @throws IOException     If an I/O error occurs during file validation or parsing.
     */
    public CLIExpand(CommandLine arguments) throws MusialException, IOException {
        this.input = Common.parseInput(arguments);
        this.output = parseOutput(arguments);
        this.vcfFiles = parseVcfFiles(arguments);
        this.vcfMeta = parseVcfMeta(arguments);
        this.dry = arguments.hasOption("d");
        if (this.dry) {
            this.overwrite = false;
            Logging.logConfig("Dry-run mode enabled, no output will be written.");
        } else if (this.output == null) {
            this.overwrite = true;
            Logging.logConfig("`output` not specified, input storage will be overwritten.");
        } else {
            this.overwrite = false;
            Logging.logConfig("`output` set to %s.".formatted(this.output));
        }
    }

    /**
     * Parses the output file path from the command-line arguments.
     * <p>
     * This method retrieves the value of the "output" option from the provided {@link CommandLine} arguments and validates the file path.
     * If the path is a directory, it appends a default file name with a timestamp and extension. If the path is invalid or cannot be
     * created, a {@link MusialException} is thrown.
     * <p>
     * The method performs the following steps:
     * <ul>
     *     <li>Checks if the "output" option is present in the arguments.</li>
     *     <li>Validates the file path and creates parent directories if necessary.</li>
     *     <li>If the path is a directory, appends a default file name with a timestamp and extension.</li>
     * </ul>
     * <p>
     * If the "output" option is not provided, the method returns {@code null}.
     *
     * @param arguments The {@link CommandLine} object containing the parsed command-line arguments.
     * @return A {@link Path} object representing the validated output file path, or {@code null} if the "output" option is not provided.
     * @throws MusialException If the path is invalid or cannot be created.
     */
    private Path parseOutput(CommandLine arguments) throws MusialException {
        if (!arguments.hasOption("output")) {
            return null;
        } else {
            Path path = Path.of(arguments.getOptionValue("output"));
            Map<String, Object> dummyConfiguration = new HashMap<>();
            dummyConfiguration.put("output", path.toString());
            return Common.parseOutput(dummyConfiguration);
        }
    }

    /**
     * Parses the list of VCF (Variant Call Format) file paths from the command-line arguments.
     * <p>
     * This method retrieves the values of the "V" option from the provided {@link CommandLine} arguments and processes them as a list of
     * file or directory paths. The paths are added to a dummy configuration map under the "vcfFiles" key, which is then passed to the
     * {@link Common#parseVcfFiles(Map)} method for further processing and validation.
     * <p>
     * The method performs the following steps:
     * <ul>
     *     <li>Retrieves the list of values for the "V" option.</li>
     *     <li>Creates a dummy configuration map and adds the retrieved values under the "vcfFiles" key.</li>
     *     <li>Delegates the parsing and validation of the VCF file paths to {@link Common#parseVcfFiles(Map)}.</li>
     * </ul>
     *
     * @param arguments The {@link CommandLine} object containing the parsed command-line arguments.
     * @return A {@link List} of {@link Path} objects representing the validated VCF file paths.
     * @throws MusialException If the VCF file paths are invalid or missing.
     * @throws IOException     If an I/O error occurs during file validation or processing.
     */
    private List<Path> parseVcfFiles(CommandLine arguments) throws MusialException, IOException {
        List<String> values = Arrays.asList(arguments.getOptionValues("V"));
        Map<String, Object> dummyConfiguration = new HashMap<>();
        dummyConfiguration.put("vcfFiles", values);
        return Common.parseVcfFiles(dummyConfiguration);
    }

    /**
     * Parses the VCF metadata file path from the command-line arguments.
     * <p>
     * This method retrieves the value of the "m" option from the provided {@link CommandLine} arguments and adds it to a dummy
     * configuration map under the "vcfMeta" key. The dummy configuration map is then passed to the {@link Common#parseVcfMeta(Map)} method
     * for further processing and validation.
     * <p>
     * If the "m" option is not provided, the dummy configuration map remains empty, and the method returns an empty map.
     *
     * @param arguments The {@link CommandLine} object containing the parsed command-line arguments.
     * @return A {@link Map} where the key is the sample ID, and the value is another map containing metadata attributes and their values.
     * @throws IOException If an I/O error occurs during file validation or processing.
     */
    private Map<String, Map<String, String>> parseVcfMeta(CommandLine arguments) throws IOException {
        Map<String, Object> dummyConfiguration = new HashMap<>();
        if (arguments.hasOption("m")) {
            dummyConfiguration.put("vcfMeta", arguments.getOptionValue("m"));
        }
        return Common.parseVcfMeta(dummyConfiguration);
    }

}
